### ISSUE TITLE
Problems starting Nginx 

### ISSUE THREAD

**Issue by cryptomulde** [openoms/bitcoin-tutorials#8] opened 2019-07-09 15:19 UTC
Hey guys,

I am trying to run electrs on my Raspiblitz.
The local setup is working fine, but when it comes to connecting via SSL it is making problems.

The script that is running into issues is the following: https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/electrs/3_Nginx_and_Certbot_for_SSL.sh

The Nginx does not start. Also when I try to start it manually it always fails one me.

The log of the script is uploaded here: https://pastebin.com/xCNNz9y8

If I can provide any additonal info please tell me what to do.

I think it has to do with the certificates for the DDNS not being created correctly.

**Comment by cryptomulde** [comment] 2019-07-09 15:30
Hey guys,

I am trying to run electrs on my Raspiblitz. 
The local setup is working fine, but when it comes to connecting via SSL it is making problems.

The script that is running into issues is the following: https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/electrs/3_Nginx_and_Certbot_for_SSL.sh

The Nginx does not start. Also when I try to start it manually it always fails one me.

The log of the script is uploaded here: https://pastebin.com/xCNNz9y8

If I can provide any additonal info please tell me what to do.

I think it has to do with the certificates for the DDNS not being created correctly.

**Comment by openoms** [comment] 2019-07-09 15:34
ok, so try to give some details please. Are you running on an otherwise clean RaspiBlitz v1.2 image? Using a  RaspberryPi 3B+? 
I presume Electrs is now working and the problem is only in this script: 
https://github.com/openoms/bitcoin-tutorials/blob/master/electrs/3_Nginx_and_Certbot_for_SSL.sh
If you have run the commands in the script one-by-one can you please tell which particular line has failed and show the output please?
I will be testing the scripts on my node and try to reproduce the issue.

**Comment by cryptomulde** [comment] 2019-07-09 15:57
v1.2 Image? Yes
Rasperry Pi 3B+? Yes
Electrs is working, as I can connect locally.

I also think it has to do with the script. 
When I run the steps one by one it gives me the error in the second step, when trying to start NGINX.
See this: https://pastebin.com/C0fGC8KB

In the `journalctl -xe` I can not find anything regarding to NGINX.

**Comment by openoms** [comment] 2019-07-11 16:28
For me it seems that the Certbot installation fails when tested on Raspbian Buster (RPi4):
There are multiple alternative methods to install certbot, for example:
https://certbot.eff.org/lets-encrypt/debiantesting-nginx

instead of the current, failing method: https://certbot.eff.org/lets-encrypt/debianother-nginx

TODO: test which method works.

**Comment by openoms** [comment] 2019-08-04 22:09
@cryptomulde might be a good time to restart installing Nginx. Worked on my RaspiBlitz 1.3 build and on an 1.2 too. Probably fixed on the side of Nginx/certbot.
rerun and follow:
`$ wget https://raw.githubusercontent.com/openoms/bitcoin-tutorials/master/electrs/3_Nginx_and_Certbot_for_SSL.sh && bash 3_Nginx_and_Certbot_for_SSL.sh`

**Comment by openoms** [comment] 2019-09-05 20:21
Installing Nginx and Certbot worked on the new 1.3 release. Please let me know if you are having further problems.

**Closed by openoms** 2019-09-05 20:21 UTC
